<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\ClubController:deleteClubAction' => function () {
    return ${($_ = isset($this->services['service_locator.gbwkqw0']) ? $this->services['service_locator.gbwkqw0'] : $this->load('getServiceLocator_Gbwkqw0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ClubController:editClubAction' => function () {
    return ${($_ = isset($this->services['service_locator.gbwkqw0']) ? $this->services['service_locator.gbwkqw0'] : $this->load('getServiceLocator_Gbwkqw0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ClubController:editEmblemAction' => function () {
    return ${($_ = isset($this->services['service_locator.gbwkqw0']) ? $this->services['service_locator.gbwkqw0'] : $this->load('getServiceLocator_Gbwkqw0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ClubController:showClubIdAction' => function () {
    return ${($_ = isset($this->services['service_locator.gbwkqw0']) ? $this->services['service_locator.gbwkqw0'] : $this->load('getServiceLocator_Gbwkqw0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController:deleteUserAction' => function () {
    return ${($_ = isset($this->services['service_locator.8ejzb7l']) ? $this->services['service_locator.8ejzb7l'] : $this->load('getServiceLocator_8ejzb7lService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController:editUserAction' => function () {
    return ${($_ = isset($this->services['service_locator.8ejzb7l']) ? $this->services['service_locator.8ejzb7l'] : $this->load('getServiceLocator_8ejzb7lService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController:showUserIdAction' => function () {
    return ${($_ = isset($this->services['service_locator.8ejzb7l']) ? $this->services['service_locator.8ejzb7l'] : $this->load('getServiceLocator_8ejzb7lService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\GameController:deleteGameAction' => function () {
    return ${($_ = isset($this->services['service_locator.zk5n3sg']) ? $this->services['service_locator.zk5n3sg'] : $this->load('getServiceLocator_Zk5n3sgService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\GameController:editGameAction' => function () {
    return ${($_ = isset($this->services['service_locator.zk5n3sg']) ? $this->services['service_locator.zk5n3sg'] : $this->load('getServiceLocator_Zk5n3sgService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\GameController:showGameIdAction' => function () {
    return ${($_ = isset($this->services['service_locator.zk5n3sg']) ? $this->services['service_locator.zk5n3sg'] : $this->load('getServiceLocator_Zk5n3sgService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\PlayerController:deletePlayerAction' => function () {
    return ${($_ = isset($this->services['service_locator.zipmw8b']) ? $this->services['service_locator.zipmw8b'] : $this->load('getServiceLocator_Zipmw8bService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\PlayerController:editPlayerAction' => function () {
    return ${($_ = isset($this->services['service_locator.zipmw8b']) ? $this->services['service_locator.zipmw8b'] : $this->load('getServiceLocator_Zipmw8bService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\PlayerController:showPlayerIdAction' => function () {
    return ${($_ = isset($this->services['service_locator.zipmw8b']) ? $this->services['service_locator.zipmw8b'] : $this->load('getServiceLocator_Zipmw8bService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\RoundController:showRoundIdAction' => function () {
    return ${($_ = isset($this->services['service_locator.man2nv2']) ? $this->services['service_locator.man2nv2'] : $this->load('getServiceLocator_Man2nv2Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:activateAction' => function () {
    return ${($_ = isset($this->services['service_locator.j7atbax']) ? $this->services['service_locator.j7atbax'] : $this->load('getServiceLocator_J7atbaxService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ClubController::deleteClubAction' => function () {
    return ${($_ = isset($this->services['service_locator.gbwkqw0']) ? $this->services['service_locator.gbwkqw0'] : $this->load('getServiceLocator_Gbwkqw0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ClubController::editClubAction' => function () {
    return ${($_ = isset($this->services['service_locator.gbwkqw0']) ? $this->services['service_locator.gbwkqw0'] : $this->load('getServiceLocator_Gbwkqw0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ClubController::editEmblemAction' => function () {
    return ${($_ = isset($this->services['service_locator.gbwkqw0']) ? $this->services['service_locator.gbwkqw0'] : $this->load('getServiceLocator_Gbwkqw0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ClubController::showClubIdAction' => function () {
    return ${($_ = isset($this->services['service_locator.gbwkqw0']) ? $this->services['service_locator.gbwkqw0'] : $this->load('getServiceLocator_Gbwkqw0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController::deleteUserAction' => function () {
    return ${($_ = isset($this->services['service_locator.8ejzb7l']) ? $this->services['service_locator.8ejzb7l'] : $this->load('getServiceLocator_8ejzb7lService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController::editUserAction' => function () {
    return ${($_ = isset($this->services['service_locator.8ejzb7l']) ? $this->services['service_locator.8ejzb7l'] : $this->load('getServiceLocator_8ejzb7lService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController::showUserIdAction' => function () {
    return ${($_ = isset($this->services['service_locator.8ejzb7l']) ? $this->services['service_locator.8ejzb7l'] : $this->load('getServiceLocator_8ejzb7lService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\GameController::deleteGameAction' => function () {
    return ${($_ = isset($this->services['service_locator.zk5n3sg']) ? $this->services['service_locator.zk5n3sg'] : $this->load('getServiceLocator_Zk5n3sgService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\GameController::editGameAction' => function () {
    return ${($_ = isset($this->services['service_locator.zk5n3sg']) ? $this->services['service_locator.zk5n3sg'] : $this->load('getServiceLocator_Zk5n3sgService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\GameController::showGameIdAction' => function () {
    return ${($_ = isset($this->services['service_locator.zk5n3sg']) ? $this->services['service_locator.zk5n3sg'] : $this->load('getServiceLocator_Zk5n3sgService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\PlayerController::deletePlayerAction' => function () {
    return ${($_ = isset($this->services['service_locator.zipmw8b']) ? $this->services['service_locator.zipmw8b'] : $this->load('getServiceLocator_Zipmw8bService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\PlayerController::editPlayerAction' => function () {
    return ${($_ = isset($this->services['service_locator.zipmw8b']) ? $this->services['service_locator.zipmw8b'] : $this->load('getServiceLocator_Zipmw8bService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\PlayerController::showPlayerIdAction' => function () {
    return ${($_ = isset($this->services['service_locator.zipmw8b']) ? $this->services['service_locator.zipmw8b'] : $this->load('getServiceLocator_Zipmw8bService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\RoundController::showRoundIdAction' => function () {
    return ${($_ = isset($this->services['service_locator.man2nv2']) ? $this->services['service_locator.man2nv2'] : $this->load('getServiceLocator_Man2nv2Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::activateAction' => function () {
    return ${($_ = isset($this->services['service_locator.j7atbax']) ? $this->services['service_locator.j7atbax'] : $this->load('getServiceLocator_J7atbaxService.php')) && false ?: '_'};
})));
