<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.zipmw8b' shared service.

return $this->services['service_locator.zipmw8b'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('player' => function () {
    $f = function (\AppBundle\Entity\Player $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Entity\Player']) ? $this->services['AppBundle\Entity\Player'] : $this->services['AppBundle\Entity\Player'] = new \AppBundle\Entity\Player()) && false ?: '_'});
}));
