<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.8ejzb7l' shared service.

return $this->services['service_locator.8ejzb7l'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('user' => function () {
    $f = function (\AppBundle\Entity\User\User $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Entity\User\User']) ? $this->services['AppBundle\Entity\User\User'] : $this->services['AppBundle\Entity\User\User'] = new \AppBundle\Entity\User\User()) && false ?: '_'});
}));
