<?php

namespace AppBundle\Repository;

/**
 * TeamBRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwayTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
