<?php

namespace AppBundle\Repository;

/**
 * TeamARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamARepository extends \Doctrine\ORM\EntityRepository
{
}
