<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\ClubController' shared autowired service.

return $this->services['AppBundle\Controller\ClubController'] = new \AppBundle\Controller\ClubController(${($_ = isset($this->services['AppBundle\Manager\ClubManager']) ? $this->services['AppBundle\Manager\ClubManager'] : $this->load('getClubManagerService.php')) && false ?: '_'});
