<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Entity\Club' shared autowired service.

return $this->services['AppBundle\Entity\Club'] = new \AppBundle\Entity\Club();
