<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\DefaultController' shared autowired service.

return $this->services['AppBundle\Controller\DefaultController'] = new \AppBundle\Controller\DefaultController(${($_ = isset($this->services['AppBundle\Manager\ClubManager']) ? $this->services['AppBundle\Manager\ClubManager'] : $this->load('getClubManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['AppBundle\Manager\UserManager']) ? $this->services['AppBundle\Manager\UserManager'] : $this->load('getUserManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.authorization_checker']) ? $this->services['security.authorization_checker'] : $this->getSecurity_AuthorizationCheckerService()) && false ?: '_'});
