<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.man2nv2' shared service.

return $this->services['service_locator.man2nv2'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('round' => function () {
    $f = function (\AppBundle\Entity\Round $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Entity\Round']) ? $this->services['AppBundle\Entity\Round'] : $this->services['AppBundle\Entity\Round'] = new \AppBundle\Entity\Round()) && false ?: '_'});
}));
