<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.zk5n3sg' shared service.

return $this->services['service_locator.zk5n3sg'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('game' => function () {
    $f = function (\AppBundle\Entity\Game $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Entity\Game']) ? $this->services['AppBundle\Entity\Game'] : $this->services['AppBundle\Entity\Game'] = new \AppBundle\Entity\Game()) && false ?: '_'});
}));
