<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\UserController' shared autowired service.

return $this->services['AppBundle\Controller\UserController'] = new \AppBundle\Controller\UserController(${($_ = isset($this->services['AppBundle\Manager\UserManager']) ? $this->services['AppBundle\Manager\UserManager'] : $this->load('getUserManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.authorization_checker']) ? $this->services['security.authorization_checker'] : $this->getSecurity_AuthorizationCheckerService()) && false ?: '_'}, new \AppBundle\Service\FlashMessagesService(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->load('getTranslatorService.php')) && false ?: '_'}));
