<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGdsxnjv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGdsxnjv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGdsxnjv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGdsxnjv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGdsxnjv\appProdProjectContainer(array(
    'container.build_hash' => 'Gdsxnjv',
    'container.build_id' => '7124d47f',
    'container.build_time' => 1548091854,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGdsxnjv');
